name: Docker Image CI for ghcr

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image to GitHub Container Registry
        run: |
          echo "${{ secrets.GH_WFLOW_DI }}" | docker login ghcr.io -u suriya-mca --password-stdin
          docker build . -t ghcr.io/suriya-mca/sqlite3:1.0.1
          docker push ghcr.io/suriya-mca/sqlite3:1.0.1

      - name: Build and push the image to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_CICD_TOKEN }}" | docker login -u suriya08 --password-stdin
          docker tag ghcr.io/suriya-mca/sqlite3:1.0.1 suriya08/sqlite3:1.0.1
          docker push suriya08/sqlite3:1.0.1
